### ISSUE TITLE
index out of bound error

### ISSUE THREAD

**Issue by elliotresearcher** [MICLab-Unicamp/CONSNet#4]
Hi, 
 when I try to train on my own dataset, it gives an error 

"index 35 is out of bounds for axis 2 with size 35"
 I am using 11 nifti scans with their masks

**Comment by OeslleLucena** [comment]
Hi @elliotresearcher, can you please print the output or your error? t will help me to answer properly your question

**Comment by elliotresearcher** [comment]
Here is the error
Running patches creation
Traceback (most recent call last):
  File "prep-train.py", line 145, in <module>
    main()
  File "prep-train.py", line 135, in main
    patches_creation(opt, patch_size, opt.max_patches, tt)
  File "prep-train.py", line 28, in patches_creation
    ,max_patches, tag, imgs_train, imgs_masks_train)
  File "E:\CONSNet-master\libs\prep_utils.py", line 169, in iterate_volume
    patch_size,max_patches,tag)
  File "E:\CONSNet-master\libs\prep_utils.py", line 142, in extract_patches
    cut = data[:,:,Hc]
IndexError: index 35 is out of bounds for axis 2 with size 35
PS E:\CONSNet-master>

**Comment by elliotresearcher** [comment]
Hi Oeslle Lucena,
     any help plz.

**Comment by OeslleLucena** [comment]
I assumed you tried the following command, right? 
`python prep-train.py -tr_original_filename data.txt -tr_consensus_filename mask.txt`
Are you trying to train your own model?
Can you please print out your `data.txt` and `mask.txt`? Also, can you please print out the shape of your data?
I need a bit more details to help you out.

**Comment by elliotresearcher** [comment]
yes i have used this command
python prep-train.py -tr_original_filename data.txt -tr_consensus_filename mask.txt
i am attaching data.txt and mask.txt files
[data.txt](https://github.com/MICLab-Unicamp/CONSNet/files/5915194/data.txt)
[mask.txt](https://github.com/MICLab-Unicamp/CONSNet/files/5915198/mask.txt)

![mask](https://user-images.githubusercontent.com/29268670/106678977-e0621900-660f-11eb-8577-edc5f52d3524.png)
I am also attaching the mask file here. I want to ask, can i use this mask or i only can use a binary mask for training.
I think this may be the issue that I am using this mask for training instead of binary, what you suggest?

**Comment by OeslleLucena** [comment]
You've got to use binary masks if you want to use the following code unless you decide to modify the training for a regression. and the way the patches are cropped out.
Can you please print out the shape of your images?

**Comment by elliotresearcher** [comment]
![dim](https://user-images.githubusercontent.com/29268670/106679732-6599fd80-6611-11eb-9001-793954eade78.png)
Here are details

**Comment by OeslleLucena** [comment]
Are you using binary masks in the mask.txt or the ones you showed me? The patches are cropped based on the binary masks you provide. It seems that at the axial slice the index the code computed is 35 which is bigger than your z shape.

**Comment by elliotresearcher** [comment]
yes i am using the mask which i have shown you, not the binary, and here are the details of mask.nii
![mid2](https://user-images.githubusercontent.com/29268670/106680831-5ddb5880-6613-11eb-88c1-375518320b66.png)

**Comment by OeslleLucena** [comment]
As you can see there is a shape mismatch between your `'test01_01_flair.nii` and `test01_01_flair_pp.nii`.
You should have the shape shape for both images. Also, make sure you do have a binary mask so the patches can be computed properly. Once you do that, the code will run fine.

**Comment by elliotresearcher** [comment]
ok thanks a lot, i'll try it. it really helped a lot.  highly appreciated
