### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by yaolp123** [MICLab-Unicamp/CONSNet#5]
Dear authors: 
    Recently I  have looking your this project and feel interested in it !could have a dataset of this project?   Thanks a lot! I am looking forward to your reply Sincerely!

Best regards.

**Comment by OeslleLucena** [comment]
Hi @yaolp123 , thanks for your interest in our work.  And yes, you can definitely have access to the data we used.
Please find it at this link https://www.ccdataset.com/download. 
Best,
